### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by eprozium** [ngn/apl#96]
Could you please tag releases?
(or maybe they're not pushed to GitHub?)
since different versions appeared in NPM but I can's see the correlation to the source.

Thanks.

**Comment by ngn** [comment]
Actually, I would prefer to delete the project from npm but `npm unpublish apl --force` fails with an error.

**Comment by eprozium** [comment]
> Actually, I would prefer to delete the project from npm

Why? NPM is the simplest way to integrate your project in applications.

**Comment by ngn** [comment]
npm forces me to make decisions about when to publish a new version. I'd rather avoid that - I'm never really sure what constitutes a release. Not a fan of semver. It's all a continuous stream of commits to me.

`package.json` can fetch libs directly from GitHub with
```json
"dependencies":{
  "apl":"ngn/apl#gh-pages"
}
```
and you can pin it down to a particular version if you use the sha1 after the `#`. I think having that makes tags and publishing to npm redundant.

**Comment by eprozium** [comment]
> you can pin it down to a particular version if you use the sha1 after the #. I think having that makes tags and publishing to npm redundant.

No it doesn't. A tag means that a certain milestone was reached and it represents something. If the number update it it is minor than it's only bug fixing (so no API or interface changes, upgrade to this new version should be safe) , if it's major than there are new features.

This is a pretty simple concept and it seems to work well for many many thousands of libraries.
I don't think APL is different in this regard.

**Comment by ngn** [comment]
In proprietary and commercial software it may make sense to use tags to keep track of what you've shipped to the customer and what APIs you commit to supporting, but this is a single-developer low-activity no-warranty free/open source project and every push is like a release.  I'm not aware of any other software that uses ngn/apl as a library through npm, so the numbering of breaking API changes isn't much of a concern.  Most visitors here try a few expressions at http://ngn.github.io/apl/web/index.html, reminisce about the good old times when they had contact with APL, and move on without even looking at the source. I'm not willing to spend any brain cycles on deciding whether this is v1.2.3 or v.1.2.4, they are both as meaningless as `b8cfa0d`.

Just because thousands of libraries do it doesn't mean it's not pointless. You may not see APL as different from the average library, but part of the culture around APL (and especially K) is to agressively fight complexity and weed out the little things you don't need. I think my lack of explicit versioning is consistent with that.
